# Generated by Django 5.2.6 on 2025-11-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, verbose_name='場所ID')),
                ('location_name', models.TextField(verbose_name='場所名')),
                ('maps_url', models.TextField(verbose_name='マップリンク')),
            ],
        ),
    ]
