# Generated by Django 5.2.6 on 2025-10-13 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='写真ID')),
                ('blog_content', models.TextField(verbose_name='ブログコンテンツ')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('picture', models.ImageField(blank=True, upload_to='photo/picture', verbose_name='写真')),
                ('camera_info', models.TextField(verbose_name='設定情報')),
                ('taken_date', models.DateField(verbose_name='撮影日付')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
                ('update_number', models.IntegerField(default=0, verbose_name='更新番号')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location', verbose_name='撮影する場所')),
            ],
        ),
    ]
