# Generated by Django 5.2.6 on 2025-11-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogPhoto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='写真ID')),
                ('picture', models.ImageField(upload_to='photo/picture', verbose_name='写真')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('update_number', models.IntegerField(default=0, verbose_name='更新番号')),
                ('blogPhoto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogPhoto.blogphoto', verbose_name='ブログ')),
            ],
        ),
    ]
