# Generated by Django 5.2.6 on 2025-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='写真ID'),
        ),
    ]
