# Generated by Django 5.2.6 on 2025-11-16 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPhoto',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ブログID')),
                ('blog_title', models.TextField(verbose_name='タイトル')),
                ('blog_body', models.TextField(verbose_name='ブログコンテンツ')),
                ('camera_info', models.TextField(verbose_name='カメラ情報')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
                ('update_number', models.IntegerField(default=0, verbose_name='更新番号')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location', verbose_name='アドレス')),
            ],
        ),
    ]
